---

- name: find vpc id
  ec2_vpc_net_info:
    filters:
      "tag:Name": "{{ vpc_name }}"
  register: found_vpcs

- name: find subnet id
  ec2_vpc_subnet_info:
    filters:
      vpc-id: "{{ found_vpcs.vpcs[0].vpc_id }}"
  register: found_subnet

- set_fact:
    subnet_id: "{{ found_subnet.subnets[0].subnet_id }}"

