---

- name: create demo vpc
  amazon.aws.ec2_vpc_net:
    name: "{{ vpc_name }}"
    cidr_block: "{{ vpc_cidr }}"
    region: "{{ ec2_region }}"
  register: vpc

- name: create subnet
  amazon.aws.ec2_vpc_subnet:
    state: present
    vpc_id: "{{ vpc.vpc.id }}"
    cidr: "{{ vpc_cidr }}"
    region: "{{ ec2_region }}"
    map_public: true
  register: subnet

- name: pass fact when running in tower
  ansible.builtin.set_stats:
    data:
      subnet: "{{ subnet }}"

- name: create internet gateway
  community.aws.ec2_vpc_igw:
    vpc_id: "{{ vpc.vpc.id }}"
    state: present
    region: "{{ ec2_region }}"
  register: igw

- name: get route table id
  community.aws.ec2_vpc_route_table_info:
    region: "{{ ec2_region }}"
    filters:
      vpc-id: "{{ vpc.vpc.id }}"
  register: route_table

- name: set up route table
  community.aws.ec2_vpc_route_table:
    vpc_id: "{{ vpc.vpc.id }}"
    region: "{{ ec2_region }}"
    route_table_id: "{{ route_table.route_tables[0].id }}"
    lookup: id
    purge_subnets: false
    subnets:
      - "{{ subnet.subnet.id }}"
    routes:
      - dest: 0.0.0.0/0
        gateway_id: "{{ igw.gateway_id }}"

- name: create security group
  amazon.aws.ec2_group:
    name: "{{ security_group }}"
    description: Ansible demo group
    vpc_id: "{{ vpc.vpc.id }}"
    region: "{{ ec2_region }}"
    rules: "{{ security_group_rules }}"
